## STATIC CONFIGURATION
log:
  level: DEBUG

# enabled at the docker compose file level
api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

http:
  routers:
    whoami:
      # By default, routers listen to every entry points
      rule: "Host(`hello.me`)"
      service: whoami
      